### ISSUE TITLE
error in convert_deeplab_resnet.py

### ISSUE THREAD

**Issue by yghlc** [isht7/pytorch-deeplab-resnet#1]
Dear all, 
   I used convert_deeplab_resnet.py to convert caffemodel, but following error. I don't know what's going on.
`[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 24:16: Message type "caffe.LayerParameter" has no field named "interp_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0514 16:39:28.816993 17207 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: data/test.prototxt
*** Check failure stack trace: ***`
I have caffe installed, but I'm not sure whether it's a correct version. 
Thank you for your attention! 

I'm not familiar with caffe. Would anyone like to share the pytorch model file (.pth) converted from caffemodel, thank you!

**Comment by isht7** [comment]
Hi, this is happening because you are not using deeplab's version of caffe. You need to install caffe available [here(deeplab-public-ver2)](https://bitbucket.org/aquariusjay/deeplab-public-ver2). I will share converted .pth files with you in a few hours.

**Comment by isht7** [comment]
Find the output .pth file of convert_deeplab_resnet.py [here](https://drive.google.com/open?id=0BxhUwxvLPO7Tb210MFB5WmQ1elE).

**Comment by yghlc** [comment]
@isht7 many thanks for your help!
