### ISSUE TITLE
Why isn't the input to model normalized?

### ISSUE THREAD

**Issue by rohitgajawada** [isht7/pytorch-deeplab-resnet#11]
Hi! I observed that your input to your model is not normalized between 0 and 1 and even has values in the 140s. Is there any reason why you did this?

**Comment by isht7** [comment]
This is not an issue. Please do not ask such things here. 
That is how images are typically passed in CNNs. This is an implementation of project written in caffe, and that is how caffe does it. Other(than images) types of data, they are generally normalized.

**Comment by isht7** [comment]
you can email me directly for questions that are not issues at isht dot dwivedi at gmail dot com

**Comment by isht7** [comment]
To be clear: Image is read(image values 0-255), mean is subtracted and the image is passed as it is(after augmentation) to the CNN.
