### ISSUE TITLE
model.eval() will change mean and var

### ISSUE THREAD

**Issue by luhc15** [isht7/pytorch-deeplab-resnet#23]
when set model.eval(), the BN layers weights and bias are fixed, but var and mean will  changed when finetuned, is there any influences if var and mean change or should set them fixed using momentum=0?

**Comment by omkar13** [comment]
When using model.eval(), mean and variance are fixed to pretrained values. BN layer's weights and bias can be fixed using requires_grad=False.

**Comment by isht7** [comment]
In my model, I have set requres_grad = False for all batch-norm parameters. Thus weights of all BN layers remain fixed. model.eval() is also used, which keeps the running mean and var fixed.
