### ISSUE TITLE
Can I train gray images using this code?

### ISSUE THREAD

**Issue by shonehang** [isht7/pytorch-deeplab-resnet#24]
I trained RGB images before, which have 3 channels.
Now I want to train gray images that have only one channel.
How should I modify this code?
Thank you very much!

**Comment by isht7** [comment]
yes, will work, just convert all images which have a single channel to a 3 channel image by repeating the same 2d matrix across all 3 channels. Put a line after [this](https://github.com/isht7/pytorch-deeplab-resnet/blob/master/train.py#L96) line to do so. Your line should be something like rgb = np.repeat(grey[:, :, np.newaxis], 3, 2).

**Comment by shonehang** [comment]
Thank you very much! I will try it according to your advice soon.
