### ISSUE TITLE
Dataset ?

### ISSUE THREAD

**Issue by Matlmr** [isht7/pytorch-deeplab-resnet#26]
Hi, great code!

Could you specify exactly which dataset corresponds to train_aug.txt and val.txt and where to get it ? It is the augmented VOC2012, right?

**Comment by isht7** [comment]
Please read Dataset under section 4.1 from [this paper](https://arxiv.org/pdf/1606.00915.pdf). They cite a paper titled "Semantic contours from inverse detectors". You can get the full dataset from that paper's website. Let me know if you have any issue searching for the dataset. Thanks!

**Comment by Matlmr** [comment]
Sorry for the late answer. On the website you indicated, the ground truth (cls and inst) is availabel as .mat files. How should I convert them to images?
Also, it seems to me that it isn't the augmented dataset that corresponds to the train_aug.txt in your repository, any way to get this one?

**Comment by isht7** [comment]
I did not augment the data, it was available as it is from the paper's website I told you about. But, files were present as .mat files and I had to extract the image and gt from them. I have uploaded my train data, you may download from [here](https://drive.google.com/file/d/11Gf5e35TdIp522OnzI_83TdSJPlL7bmb/view?usp=sharing) (please request access if it is not shared with you, I will share with you).

**Comment by Matlmr** [comment]
I requested access. Thanks a lot!

**Comment by isht7** [comment]
I gave you access.
