### ISSUE TITLE
How to train pytorch_deeplab_resnet by using my own data?

### ISSUE THREAD

**Issue by yghlc** [isht7/pytorch-deeplab-resnet#3]
Hello,
   I have my own data, also can be converted to the format like VOC2012. But my data have only two classes such as the target and the background.
  How to set the number of class?
Thanks

**Comment by isht7** [comment]
@yghlc A new [branch](https://github.com/isht7/pytorch-deeplab-resnet/tree/custom_maxLabel) with custom data support has been added. During training and evaluation new flag "NoLabels" is added(more in README, and do `python train.py -h` for information about flag.). Please check if it serves your purpose. This branch would be merged with master after some more testing.

**Comment by isht7** [comment]
Now, the master branch can also be used to train using your own data.
