### ISSUE TITLE
how does iter_size work?

### ISSUE THREAD

**Issue by wppply** [isht7/pytorch-deeplab-resnet#34]
In the readme.md, you claims that the iter_size option could increase the batchsize  to batchsize*iter_size.

However, I did not see any code about this except divide the loss by iter_size.

Could you give more details? thanks

**Comment by isht7** [comment]
Gradient is accumulated for `iter_size` iterations and then applied. So, gradients are applied only once after `iter_size`iterations. The division you are referring to is to average the accumulated gradients.
